'use client';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import type { User } from '@supabase/supabase-js';
import { Activity, ArrowRight, BookOpen, BriefcaseBusiness, CalendarDays, ChevronRight, ClipboardList, FileText, LayoutDashboard, LogOut, Menu, Plus, Search, ShieldCheck, Users, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { type Department, type Expediente, type Movement, type Parte, type Personnel, type Profile, type Service, estadosParte, isoHoy, rolesCentrales, tiposMovimiento, turnos } from '@/lib/types';

type Tab = 'inicio'|'personal'|'movimientos'|'expedientes'|'parte';
type FormName = 'persona'|'movimiento'|'expediente'|null;
const menu = [{id:'inicio',label:'Inicio',icon:LayoutDashboard},{id:'personal',label:'Personal',icon:Users},{id:'movimientos',label:'Movimientos',icon:Activity},{id:'expedientes',label:'Expedientes',icon:FileText},{id:'parte',label:'Parte diario',icon:ClipboardList}] as const;
const emptyPerson = {lp:'',apellido:'',nombres:'',jerarquia:'',dni:'',cuil:'',telefono:'',email:'',funcion:'',horario:'',turno:'',fecha_ingreso:'',observaciones:'',activo:true};
function errorText(e:unknown){return e instanceof Error?e.message:'No se pudo completar la operación.'}
function Input({label,value,onChange,type='text',required=false}: {label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}) {return <label className="field"><span>{label}</span><input type={type} value={value} required={required} onChange={e=>onChange(e.target.value)}/></label>}
function Notice({children,kind='error'}:{children:React.ReactNode;kind?:'error'|'success'}) {return <div className={`notice ${kind}`} role="status">{children}</div>}
export default function Home(){
  const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null);
  const [authLoading,setAuthLoading]=useState(true),[authError,setAuthError]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const [tab,setTab]=useState<Tab>('inicio'),[mobileOpen,setMobileOpen]=useState(false);
  const [departments,setDepartments]=useState<Department[]>([]),[services,setServices]=useState<Service[]>([]);
  const [depId,setDepId]=useState(''),[srvId,setSrvId]=useState(''),[query,setQuery]=useState(''),[appliedQuery,setAppliedQuery]=useState('');
  const [people,setPeople]=useState<Personnel[]>([]),[movements,setMovements]=useState<Movement[]>([]),[expedientes,setExpedientes]=useState<Expediente[]>([]),[parts,setParts]=useState<Parte[]>([]);
  const [selected,setSelected]=useState<Personnel|null>(null),[form,setForm]=useState<FormName>(null),[editing,setEditing]=useState<Personnel|null>(null);
  const [personDraft,setPersonDraft]=useState({...emptyPerson}),[moveDraft,setMoveDraft]=useState({personal_id:'',tipo:'LICENCIA ANUAL',subtipo:'',fecha_desde:isoHoy(),fecha_hasta:isoHoy(),hora_desde:'',hora_hasta:'',descripcion:''});
  const [expDraft,setExpDraft]=useState({numero:'',asunto:'',tipo:'',fecha_inicio:isoHoy(),personal_id:''});
  const [fecha,setFecha]=useState(isoHoy()),[turno,setTurno]=useState<string>('MAÑANA'),[parteDraft,setParteDraft]=useState<Record<string,{estado:string;hora_desde:string;hora_hasta:string;observaciones:string}>>({});
  const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);
  const central=!!profile&&rolesCentrales.includes(profile.rol),canEdit=!!profile&&['SUPER_ADMIN','RRHH_ADMIN'].includes(profile.rol),canMove=!!profile&&rolesCentrales.includes(profile.rol),canPart=!!profile&&profile.rol!=='CONSULTA';
  const canCreateExp=!!profile&&profile.rol!=='CONSULTA';
  const visibleServices=useMemo(()=>services.filter(s=>s.departamento_id===depId),[services,depId]);
  const effectiveService=srvId&&visibleServices.some(s=>s.id===srvId)?srvId:'';
  const refresh=()=>setRevision(n=>n+1);
  useEffect(()=>{
    let active=true;
    try { const db=supabase();
      void db.auth.getUser().then(({data,error})=>{if(!active)return;setUser(error?null:data.user);setAuthLoading(false)}).catch(e=>{if(active){setAuthError(errorText(e));setAuthLoading(false)}});
      const {data:auth}=db.auth.onAuthStateChange((_event,session)=>{if(active)setUser(session?.user??null)});
      return ()=>{active=false;auth.subscription.unsubscribe()};
    }catch(e){setAuthError(errorText(e));setAuthLoading(false)}
  },[]);
  useEffect(()=>{
    if(!user){setProfile(null);setDepartments([]);setServices([]);return}
    let active=true;
    async function init(){try{
      const db=supabase();const {data:p,error:pe}=await db.from('profiles').select('id,nombre,apellido,rol,departamento_id,servicio_id,activo').eq('id',user!.id).maybeSingle();
      if(pe)throw pe;if(!active)return;
      if(!p||!p.activo){setProfile(null);setAuthError('Tu cuenta no tiene un perfil SGA habilitado. Solicitá acceso al administrador.');return}
      setProfile(p as Profile);setAuthError('');
      const [ds,ss]=await Promise.all([db.from('departments').select('id,nombre').eq('activo',true).order('nombre'),db.from('services').select('id,nombre,departamento_id').eq('activo',true).order('nombre')]);
      if(ds.error)throw ds.error;if(ss.error)throw ss.error;if(!active)return;
      const d=(ds.data??[]) as Department[],s=(ss.data??[]) as Service[];
      setDepartments(d);setServices(s);const dep=(p as Profile).departamento_id||d[0]?.id||'';
      setDepId(dep);setSrvId((p as Profile).servicio_id||s.find(x=>x.departamento_id===dep)?.id||'');
    }catch(e){if(active)setAuthError(errorText(e))}}
    void init();return ()=>{active=false}
  },[user]);
  const load=useCallback(async()=>{
    if(!profile)return;
    setLoading(true);setMessage('');
    try{const db=supabase();
      if(tab==='inicio'){
        const [p,m,e]=await Promise.all([db.from('personnel').select('id',{count:'exact',head:true}),db.from('movements').select('id',{count:'exact',head:true}).eq('estado','REGISTRADO'),db.from('expedientes').select('id',{count:'exact',head:true})]);
        if(p.error||m.error||e.error)throw p.error||m.error||e.error;
        setCounters([p.count??0,m.count??0,e.count??0]);
      }else if(tab==='personal'){
        let req=db.from('personnel').select('id,lp,apellido,nombres,jerarquia,dni,cuil,telefono,email,funcion,horario,turno,fecha_ingreso,observaciones,activo,departamento_id,servicio_id').order('apellido').limit(100);
        if(depId)req=req.eq('departamento_id',depId);if(effectiveService)req=req.eq('servicio_id',effectiveService);
        const q=appliedQuery.trim().replace(/[^\p{L}\p{N} -]/gu,'').slice(0,80);
        if(q)req=req.or(`lp.ilike.%${q}%,apellido.ilike.%${q}%,nombres.ilike.%${q}%`);
        const {data,error}=await req;if(error)throw error;setPeople((data??[]) as Personnel[]);
      }else if(tab==='movimientos'){
        let req=db.from('movements').select('id,personal_id,tipo,subtipo,fecha_desde,fecha_hasta,hora_desde,hora_hasta,descripcion,estado,departamento_id,servicio_id,personal:personnel!movements_personal_id_fkey(lp,apellido,nombres)').order('fecha_desde',{ascending:false}).limit(100);
        if(depId)req=req.eq('departamento_id',depId);if(effectiveService)req=req.eq('servicio_id',effectiveService);
        const {data,error}=await req;if(error)throw error;setMovements((data??[]) as unknown as Movement[]);
      }else if(tab==='expedientes'){
        let req=db.from('expedientes').select('id,numero,asunto,tipo,estado,fecha_inicio,personal_id,departamento_id,servicio_id').order('fecha_inicio',{ascending:false}).limit(100);
        if(depId)req=req.eq('departamento_id',depId);if(effectiveService)req=req.eq('servicio_id',effectiveService);
        const {data,error}=await req;if(error)throw error;setExpedientes((data??[]) as Expediente[]);
      }else if(tab==='parte'){
        if(!effectiveService){setPeople([]);setParts([]);return}
        const [p,entries,m]=await Promise.all([
          db.from('personnel').select('id,lp,apellido,nombres,jerarquia,dni,cuil,telefono,email,funcion,horario,turno,fecha_ingreso,observaciones,activo,departamento_id,servicio_id').eq('servicio_id',effectiveService).eq('activo',true).order('apellido').limit(250),
          db.from('parte_entries').select('id,fecha,personal_id,turno,estado,hora_desde,hora_hasta,observaciones').eq('fecha',fecha).eq('turno',turno).eq('servicio_id',effectiveService),
          db.from('movements').select('id,personal_id,tipo,subtipo,fecha_desde,fecha_hasta,hora_desde,hora_hasta,descripcion,estado,departamento_id,servicio_id').eq('servicio_id',effectiveService).eq('estado','REGISTRADO').lte('fecha_desde',fecha).gte('fecha_hasta',fecha).limit(500)
        ]);
        if(p.error||entries.error||m.error)throw p.error||entries.error||m.error;
        const ps=(p.data??[]) as Personnel[],es=(entries.data??[]) as Parte[],ms=(m.data??[]) as Movement[];
        setPeople(ps);setParts(es);const draft:Record<string,{estado:string;hora_desde:string;hora_hasta:string;observaciones:string}>={};
        for(const person of ps){const old=es.find(v=>v.personal_id===person.id),auto=ms.find(v=>v.personal_id===person.id&&estadosParte.includes(v.tipo));
          draft[person.id]={estado:old?.estado||auto?.tipo||'PRESENTE',hora_desde:old?.hora_desde||auto?.hora_desde||'',hora_hasta:old?.hora_hasta||auto?.hora_hasta||'',observaciones:old?.observaciones||''};
        }setParteDraft(draft);
      }
    }catch(e){setMessage(errorText(e))}finally{setLoading(false)}
  },[profile,tab,depId,effectiveService,appliedQuery,fecha,turno]);
  const [counters,setCounters]=useState([0,0,0]);
  useEffect(()=>{void load()},[load,revision]);
  async function login(e:FormEvent){e.preventDefault();setSaving(true);setAuthError('');try{const {error}=await supabase().auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('')}catch(e){setAuthError(errorText(e))}finally{setSaving(false)}}
  async function logout(){await supabase().auth.signOut();setProfile(null);setUser(null);setTab('inicio')}
  function openPerson(person?:Personnel){setEditing(person??null);setPersonDraft(person?{lp:person.lp,apellido:person.apellido,nombres:person.nombres,jerarquia:person.jerarquia??'',dni:person.dni??'',cuil:person.cuil??'',telefono:person.telefono??'',email:person.email??'',funcion:person.funcion??'',horario:person.horario??'',turno:person.turno??'',fecha_ingreso:person.fecha_ingreso??'',observaciones:person.observaciones??'',activo:person.activo}:{...emptyPerson});setForm('persona')}
  async function savePerson(e:FormEvent){e.preventDefault();if(!canEdit||!depId||!effectiveService)return;setSaving(true);setMessage('');try{
    const payload={...personDraft,lp:personDraft.lp.trim(),apellido:personDraft.apellido.trim(),nombres:personDraft.nombres.trim(),dni:personDraft.dni||null,cuil:personDraft.cuil||null,fecha_ingreso:personDraft.fecha_ingreso||null,departamento_id:depId,servicio_id:effectiveService};
    const db=supabase();const result=editing?await db.from('personnel').update(payload).eq('id',editing.id):await db.from('personnel').insert(payload);
    if(result.error)throw result.error;setForm(null);refresh();setMessage('Personal guardado correctamente.');
  }catch(e){setMessage(errorText(e))}finally{setSaving(false)}}
  async function saveMovement(e:FormEvent){e.preventDefault();if(!canMove||!effectiveService||!depId)return;setSaving(true);setMessage('');try{
    const person=people.find(p=>p.id===moveDraft.personal_id);if(!person)throw Error('Seleccioná una persona del servicio.');
    if(moveDraft.fecha_hasta<moveDraft.fecha_desde)throw Error('La fecha hasta no puede ser anterior a desde.');
    if(moveDraft.tipo==='GUARDIA PAGA'&&(!moveDraft.hora_desde||!moveDraft.hora_hasta||moveDraft.hora_hasta<=moveDraft.hora_desde))throw Error('Ingresá un horario válido para la guardia paga.');
    const {error}=await supabase().from('movements').insert({personal_id:person.id,tipo:moveDraft.tipo,subtipo:moveDraft.subtipo||null,fecha_desde:moveDraft.fecha_desde,fecha_hasta:moveDraft.fecha_hasta,hora_desde:moveDraft.tipo==='GUARDIA PAGA'?moveDraft.hora_desde:null,hora_hasta:moveDraft.tipo==='GUARDIA PAGA'?moveDraft.hora_hasta:null,descripcion:moveDraft.descripcion||null,departamento_id:depId,servicio_id:effectiveService});
    if(error)throw error;setForm(null);refresh();setMessage('Movimiento registrado.');
  }catch(e){setMessage(errorText(e))}finally{setSaving(false)}}
  async function saveExp(e:FormEvent){e.preventDefault();if(!canCreateExp||!depId||!effectiveService)return;setSaving(true);setMessage('');try{
    const {error}=await supabase().from('expedientes').insert({numero:expDraft.numero.trim(),asunto:expDraft.asunto.trim(),tipo:expDraft.tipo||null,fecha_inicio:expDraft.fecha_inicio,personal_id:expDraft.personal_id||null,departamento_id:depId,servicio_id:effectiveService});
    if(error)throw error;setForm(null);refresh();setMessage('Expediente creado.');
  }catch(e){setMessage(errorText(e))}finally{setSaving(false)}}
  async function saveParts(){if(!canPart||!depId||!effectiveService)return;setSaving(true);setMessage('');try{
    const rows=people.map(p=>({fecha,personal_id:p.id,departamento_id:depId,servicio_id:effectiveService,turno,estado:parteDraft[p.id]?.estado||'PRESENTE',hora_desde:parteDraft[p.id]?.estado==='GUARDIA PAGA'?parteDraft[p.id]?.hora_desde||null:null,hora_hasta:parteDraft[p.id]?.estado==='GUARDIA PAGA'?parteDraft[p.id]?.hora_hasta||null:null,observaciones:parteDraft[p.id]?.observaciones||null}));
    for(const row of rows)if(row.estado==='GUARDIA PAGA'&&(!row.hora_desde||!row.hora_hasta||row.hora_hasta<=row.hora_desde))throw Error('La guardia paga requiere un horario válido.');
    if(rows.length){const {error}=await supabase().from('parte_entries').upsert(rows,{onConflict:'fecha,personal_id,turno'});if(error)throw error}
    setMessage(`Parte de ${turno.toLowerCase()} guardado (${rows.length} registros).`);refresh();
  }catch(e){setMessage(errorText(e))}finally{setSaving(false)}}
  function changeTab(next:Tab){setTab(next);setSelected(null);setMessage('');setMobileOpen(false)}
  if(authLoading)return <main className="center"><div className="loading-mark">SGA</div><p>Verificando acceso…</p></main>;
  if(!user)return <main className="auth-screen"><div className="auth-decor"/><section className="auth-card"><span className="brand-mark">S✦</span><div className="eyebrow">PLATAFORMA INSTITUCIONAL</div><h1>Gestión administrativa,<br/><span>en un solo lugar.</span></h1><p>Ingresá con tu cuenta autorizada para acceder a la información de tu servicio.</p><form onSubmit={login} className="auth-form"><Input label="Correo electrónico" value={email} onChange={setEmail} type="email" required/><Input label="Contraseña" value={password} onChange={setPassword} type="password" required/>{authError&&<Notice>{authError}</Notice>}<button disabled={saving} className="primary" type="submit">{saving?'Ingresando…':'Ingresar al sistema'} <ArrowRight size={18}/></button></form><div className="security"><ShieldCheck size={17}/> Acceso restringido · Datos protegidos</div></section><div className="auth-foot">SGA · Sistema de Gestión Administrativa</div></main>;
  if(!profile)return <main className="center"><ShieldCheck size={38}/><h1>Acceso pendiente</h1><p>{authError||'No se encontró tu perfil activo.'}</p><button className="primary" onClick={logout}>Cerrar sesión</button></main>;
  return <div className="shell">
    <aside className={`sidebar ${mobileOpen?'open':''}`}><div className="side-top"><div className="brand"><span className="brand-mark">S✦</span><div><strong>SGA</strong><small>Gestión Administrativa</small></div></div><button className="mobile-close icon-btn" aria-label="Cerrar menú" onClick={()=>setMobileOpen(false)}><X size={20}/></button></div><div className="nav-label">ESPACIO DE TRABAJO</div><nav aria-label="Navegación principal">{menu.map(item=>{const Icon=item.icon;return <button key={item.id} className={`nav-link ${tab===item.id?'active':''}`} onClick={()=>changeTab(item.id)}><Icon size={19}/><span>{item.label}</span>{tab===item.id&&<ChevronRight size={16} className="nav-chevron"/>}</button>})}</nav><div className="side-bottom"><div className="secure-badge"><ShieldCheck size={18}/><div><strong>Entorno protegido</strong><span>Acceso según rol y servicio</span></div></div><button className="signout" onClick={logout}><LogOut size={18}/> Cerrar sesión</button></div></aside>
    {mobileOpen&&<button className="scrim" aria-label="Cerrar navegación" onClick={()=>setMobileOpen(false)}/>}
    <main className="main"><header className="topbar"><button className="menu-trigger icon-btn" aria-label="Abrir menú" onClick={()=>setMobileOpen(true)}><Menu size={23}/></button><span className="breadcrumb">SGA <ChevronRight size={14}/> <b>{menu.find(v=>v.id===tab)?.label}</b></span><div className="account"><span className="avatar">{profile.nombre.slice(0,1)}{profile.apellido.slice(0,1)}</span><div><strong>{profile.nombre} {profile.apellido}</strong><small>{profile.rol.replaceAll('_',' ')}</small></div></div></header>
    <div className="content"><div className="page-heading"><div><span className="eyebrow">SISTEMA DE GESTIÓN ADMINISTRATIVA</span><h1>{tab==='inicio'?`Hola, ${profile.nombre} 👋`:menu.find(v=>v.id===tab)?.label}</h1><p>{tab==='inicio'?'Tu espacio de trabajo, organizado y actualizado.':tab==='personal'?'Consultá fichas laborales y datos del personal.':tab==='movimientos'?'Novedades y movimientos administrativos por servicio.':tab==='expedientes'?'Seguimiento de expedientes registrados.':'Cargá las novedades por día, servicio y turno.'}</p></div><span className="today"><CalendarDays size={17}/> {new Intl.DateTimeFormat('es-AR',{dateStyle:'medium'}).format(new Date())}</span></div>
    {message&&<Notice kind={message.includes('correctamente')||message.includes('registrado')||message.includes('guardado')||message.includes('creado')?'success':'error'}>{message}</Notice>}
    {tab==='inicio'&&<><div className="stats"><div className="stat"><span className="stat-icon lavender"><Users/></span><p>Personal visible</p><strong>{counters[0].toLocaleString('es-AR')}</strong><small>Según tus permisos</small></div><div className="stat"><span className="stat-icon blue"><Activity/></span><p>Movimientos activos</p><strong>{counters[1].toLocaleString('es-AR')}</strong><small>Registros no anulados</small></div><div className="stat"><span className="stat-icon green"><BriefcaseBusiness/></span><p>Expedientes</p><strong>{counters[2].toLocaleString('es-AR')}</strong><small>En tu ámbito</small></div></div><div className="section-title"><h2>Accesos rápidos</h2><p>Continuá con tus tareas habituales</p></div><div className="quick-grid">{menu.slice(1).map(item=>{const Icon=item.icon;return <button key={item.id} className="quick-card" onClick={()=>changeTab(item.id)}><span className="quick-icon"><Icon size={23}/></span><strong>{item.label}</strong><span>Abrir módulo <ArrowRight size={16}/></span></button>})}</div><div className="hint"><BookOpen size={20}/><div><strong>Migración en etapas</strong><p>Esta primera versión incluye fichas de personal, movimientos, expedientes básicos y carga de parte diario. Los circuitos especializados del sistema anterior se migrarán por separado.</p></div></div></>}
    {tab!=='inicio'&&<div className="toolbar"><div className="filters"><label className="select-field"><span>Departamento</span><select value={depId} disabled={!central} onChange={e=>{const v=e.target.value;setDepId(v);setSrvId(services.find(s=>s.departamento_id===v)?.id||'')}}>{departments.map(d=><option key={d.id} value={d.id}>{d.nombre}</option>)}</select></label><label className="select-field"><span>Servicio</span><select value={effectiveService} disabled={!!profile.servicio_id} onChange={e=>setSrvId(e.target.value)}><option value="">Todos los servicios</option>{visibleServices.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label>{tab==='parte'&&<><label className="select-field"><span>Fecha</span><input type="date" value={fecha} onChange={e=>setFecha(e.target.value)}/></label><label className="select-field"><span>Turno</span><select value={turno} onChange={e=>setTurno(e.target.value)}>{turnos.map(t=><option key={t}>{t}</option>)}</select></label></>}</div><div className="toolbar-actions">{tab==='personal'&&canEdit&&<button className="primary" disabled={!effectiveService} onClick={()=>openPerson()}><Plus size={17}/> Nuevo personal</button>}{tab==='movimientos'&&canMove&&<button className="primary" disabled={!effectiveService} onClick={async()=>{const {data,error}=await supabase().from('personnel').select('id,lp,apellido,nombres,departamento_id,servicio_id').eq('servicio_id',effectiveService).limit(250);if(error){setMessage(error.message);return}setPeople((data??[]) as Personnel[]);setMoveDraft({personal_id:'',tipo:'LICENCIA ANUAL',subtipo:'',fecha_desde:isoHoy(),fecha_hasta:isoHoy(),hora_desde:'',hora_hasta:'',descripcion:''});setForm('movimiento')}}><Plus size={17}/> Nuevo movimiento</button>}{tab==='expedientes'&&canCreateExp&&<button className="primary" disabled={!effectiveService} onClick={()=>{setExpDraft({numero:'',asunto:'',tipo:'',fecha_inicio:isoHoy(),personal_id:''});setForm('expediente')}}><Plus size={17}/> Nuevo expediente</button>}</div></div>}
    {tab==='personal'&&<div className="panel"><div className="panel-heading"><h2>Directorio de personal</h2><div className="search-box"><Search size={18}/><input placeholder="Buscar por LP, apellido o nombre" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')setAppliedQuery(query)}}/><button onClick={()=>setAppliedQuery(query)}>Buscar</button></div></div>{loading?<div className="empty">Cargando personal…</div>:people.length===0?<div className="empty">No se encontraron personas. Revisá el servicio o la búsqueda.</div>:<div className="table-scroll"><table><thead><tr><th>LP</th><th>Apellido y nombres</th><th>Jerarquía</th><th>Función</th><th>Estado</th><th></th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td className="mono">{p.lp}</td><td><strong>{p.apellido}, {p.nombres}</strong></td><td>{p.jerarquia||'—'}</td><td>{p.funcion||'—'}</td><td><span className={`pill ${p.activo?'ok':'muted'}`}>{p.activo?'Activo':'Inactivo'}</span></td><td><button className="text-button" onClick={()=>setSelected(p)}>Ver ficha <ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>}<div className="panel-foot">Se muestran hasta 100 resultados. Filtrá para refinar la búsqueda.</div></div>}
    {tab==='movimientos'&&<div className="panel"><div className="panel-heading"><h2>Movimientos registrados</h2><small>Últimos 100 movimientos visibles</small></div>{loading?<div className="empty">Cargando movimientos…</div>:movements.length===0?<div className="empty">No hay movimientos en este ámbito.</div>:<div className="table-scroll"><table><thead><tr><th>Personal</th><th>Tipo</th><th>Desde</th><th>Hasta</th><th>Estado</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td><strong>{m.personal?`${m.personal.apellido}, ${m.personal.nombres}`:'Personal'}</strong><small className="subline">{m.personal?.lp||''}</small></td><td>{m.tipo}</td><td>{m.fecha_desde}</td><td>{m.fecha_hasta||'—'}</td><td><span className={`pill ${m.estado==='REGISTRADO'?'ok':'muted'}`}>{m.estado}</span></td></tr>)}</tbody></table></div>}</div>}
    {tab==='expedientes'&&<div className="panel"><div className="panel-heading"><h2>Expedientes</h2><small>Últimos 100 registros</small></div>{loading?<div className="empty">Cargando expedientes…</div>:expedientes.length===0?<div className="empty">Todavía no hay expedientes registrados.</div>:<div className="table-scroll"><table><thead><tr><th>Número</th><th>Asunto</th><th>Tipo</th><th>Fecha</th><th>Estado</th></tr></thead><tbody>{expedientes.map(e=><tr key={e.id}><td className="mono">{e.numero}</td><td><strong>{e.asunto}</strong></td><td>{e.tipo||'—'}</td><td>{e.fecha_inicio}</td><td><span className="pill muted">{e.estado}</span></td></tr>)}</tbody></table></div>}</div>}
    {tab==='parte'&&<div className="panel"><div className="panel-heading"><div><h2>Planilla de {turno.toLowerCase()}</h2><small>{fecha} · {visibleServices.find(s=>s.id===effectiveService)?.nombre||'Seleccioná un servicio'}</small></div>{canPart&&<button className="primary" onClick={saveParts} disabled={saving||loading||!effectiveService||people.length===0}>{saving?'Guardando…':'Guardar parte'}</button>}</div>{!effectiveService?<div className="empty">Elegí un servicio para cargar su parte.</div>:loading?<div className="empty">Cargando parte…</div>:people.length===0?<div className="empty">No hay personal activo en este servicio.</div>:<div className="table-scroll"><table><thead><tr><th>Personal</th><th>Estado</th><th>Horario guardia</th><th>Observaciones</th></tr></thead><tbody>{people.map(p=>{const d=parteDraft[p.id];return <tr key={p.id}><td><strong>{p.apellido}, {p.nombres}</strong><small className="subline">LP {p.lp}</small></td><td><select aria-label={`Estado de ${p.apellido}`} disabled={!canPart} value={d?.estado||'PRESENTE'} onChange={e=>setParteDraft(old=>({...old,[p.id]:{...old[p.id],estado:e.target.value}}))}>{estadosParte.map(s=><option key={s}>{s}</option>)}</select></td><td>{d?.estado==='GUARDIA PAGA'?<div className="time-pair"><input aria-label="Hora desde" type="time" disabled={!canPart} value={d.hora_desde} onChange={e=>setParteDraft(old=>({...old,[p.id]:{...old[p.id],hora_desde:e.target.value}}))}/><input aria-label="Hora hasta" type="time" disabled={!canPart} value={d.hora_hasta} onChange={e=>setParteDraft(old=>({...old,[p.id]:{...old[p.id],hora_hasta:e.target.value}}))}/></div>:<span className="subtle">—</span>}</td><td><input aria-label={`Observaciones de ${p.apellido}`} className="note-input" disabled={!canPart} value={d?.observaciones||''} maxLength={500} onChange={e=>setParteDraft(old=>({...old,[p.id]:{...old[p.id],observaciones:e.target.value}}))}/></td></tr>})}</tbody></table></div>}<div className="panel-foot">Los movimientos vigentes se sugieren automáticamente al cargar. Revisá los estados antes de guardar. Esta versión no realiza cierre formal del parte.</div></div>}
    </div></main>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-sheet" role="dialog" aria-modal="true" aria-label="Ficha de personal" onClick={e=>e.stopPropagation()}><div className="modal-head"><span className="eyebrow">FICHA DE PERSONAL</span><button className="icon-btn" onClick={()=>setSelected(null)} aria-label="Cerrar"><X/></button></div><div className="person-avatar">{selected.apellido[0]}{selected.nombres[0]}</div><h2>{selected.apellido}, {selected.nombres}</h2><p>LP {selected.lp} · {selected.jerarquia||'Personal'}</p><div className="detail-grid">{([['DNI',selected.dni],['CUIL',selected.cuil],['Teléfono',selected.telefono],['Correo',selected.email],['Función',selected.funcion],['Horario',selected.horario],['Turno',selected.turno],['Fecha de ingreso',selected.fecha_ingreso],['Observaciones',selected.observaciones]] as const).map(([k,v])=><div key={k}><span>{k}</span><strong>{v||'Sin registrar'}</strong></div>)}</div>{canEdit&&<button className="primary" onClick={()=>{openPerson(selected);setSelected(null)}}>Editar ficha</button>}</section></div>}
    {form&&<div className="modal-backdrop" onClick={()=>setForm(null)}><section className="form-modal" role="dialog" aria-modal="true" aria-label={`Formulario de ${form}`} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">REGISTRO ADMINISTRATIVO</span><h2>{form==='persona'?(editing?'Editar personal':'Nuevo personal'):form==='movimiento'?'Nuevo movimiento':'Nuevo expediente'}</h2></div><button className="icon-btn" onClick={()=>setForm(null)} aria-label="Cerrar"><X/></button></div>{form==='persona'&&<form onSubmit={savePerson} className="form-grid">{(['lp','apellido','nombres','jerarquia','dni','cuil','telefono','email','funcion','horario','turno','fecha_ingreso','observaciones'] as const).map(k=><Input key={k} label={{lp:'LP',apellido:'Apellido',nombres:'Nombres',jerarquia:'Jerarquía',dni:'DNI',cuil:'CUIL',telefono:'Teléfono',email:'Email',funcion:'Función',horario:'Horario',turno:'Turno',fecha_ingreso:'Fecha de ingreso',observaciones:'Observaciones'}[k]} value={String(personDraft[k])} required={['lp','apellido','nombres'].includes(k)} type={k==='fecha_ingreso'?'date':k==='email'?'email':'text'} onChange={v=>setPersonDraft(old=>({...old,[k]:v}))}/>)}<label className="field"><span>Estado</span><select value={personDraft.activo?'true':'false'} onChange={e=>setPersonDraft(old=>({...old,activo:e.target.value==='true'}))}><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button className="primary form-submit" disabled={saving}>{saving?'Guardando…':'Guardar personal'}</button></form>}
    {form==='movimiento'&&<form onSubmit={saveMovement} className="form-grid"><label className="field wide"><span>Personal</span><select required value={moveDraft.personal_id} onChange={e=>setMoveDraft(old=>({...old,personal_id:e.target.value}))}><option value="">Seleccionar personal</option>{people.map(p=><option key={p.id} value={p.id}>{p.lp} — {p.apellido}, {p.nombres}</option>)}</select></label><label className="field"><span>Tipo</span><select value={moveDraft.tipo} onChange={e=>setMoveDraft(old=>({...old,tipo:e.target.value}))}>{tiposMovimiento.map(t=><option key={t}>{t}</option>)}</select></label><Input label="Subtipo (opcional)" value={moveDraft.subtipo} onChange={v=>setMoveDraft(old=>({...old,subtipo:v}))}/><Input label="Desde" value={moveDraft.fecha_desde} type="date" required onChange={v=>setMoveDraft(old=>({...old,fecha_desde:v}))}/><Input label="Hasta" value={moveDraft.fecha_hasta} type="date" required onChange={v=>setMoveDraft(old=>({...old,fecha_hasta:v}))}/>{moveDraft.tipo==='GUARDIA PAGA'&&<><Input label="Hora desde" type="time" value={moveDraft.hora_desde} required onChange={v=>setMoveDraft(old=>({...old,hora_desde:v}))}/><Input label="Hora hasta" type="time" value={moveDraft.hora_hasta} required onChange={v=>setMoveDraft(old=>({...old,hora_hasta:v}))}/></>}<label className="field wide"><span>Descripción</span><textarea value={moveDraft.descripcion} onChange={e=>setMoveDraft(old=>({...old,descripcion:e.target.value}))}/></label><button className="primary form-submit" disabled={saving}>{saving?'Registrando…':'Registrar movimiento'}</button></form>}
    {form==='expediente'&&<form onSubmit={saveExp} className="form-grid"><Input label="Número de expediente" value={expDraft.numero} required onChange={v=>setExpDraft(old=>({...old,numero:v}))}/><Input label="Tipo" value={expDraft.tipo} onChange={v=>setExpDraft(old=>({...old,tipo:v}))}/><label className="field wide"><span>Asunto</span><textarea required value={expDraft.asunto} onChange={e=>setExpDraft(old=>({...old,asunto:e.target.value}))}/></label><Input label="Fecha de inicio" type="date" required value={expDraft.fecha_inicio} onChange={v=>setExpDraft(old=>({...old,fecha_inicio:v}))}/><button className="primary form-submit" disabled={saving}>{saving?'Guardando…':'Crear expediente'}</button></form>}
    </section></div>}
  </div>;
}
